src/Entity/Quote.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuoteRepository")
 */
class Quote
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $status;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="quotes", cascade={"persist"})
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $send_to_user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $approved_by_user;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Order", mappedBy="quote", cascade={"persist", "remove"})
     */
    private $quote_order;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSendToUser(): ?\DateTimeInterface
    {
        return $this->send_to_user;
    }

    public function setSendToUser(?\DateTimeInterface $send_to_user): self
    {
        $this->send_to_user = $send_to_user;

        return $this;
    }

    public function getApprovedByUser(): ?\DateTimeInterface
    {
        return $this->approved_by_user;
    }

    public function setApprovedByUser(?\DateTimeInterface $approved_by_user): self
    {
        $this->approved_by_user = $approved_by_user;

        return $this;
    }

    public function getQuoteOrder(): ?Order
    {
        return $this->quote_order;
    }

    public function setQuoteOrder(Order $quote_order): self
    {
        $this->quote_order = $quote_order;

        // set the owning side of the relation if necessary
        if ($quote_order->getQuote() !== $this) {
            $quote_order->setQuote($this);
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->id;
    }
}

src/Form/QuoteType.php
<?php

namespace App\Form;

use App\Entity\Quote;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuoteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('created_at')
            ->add('status')
            ->add('price')
            ->add('send_to_user')
            ->add('approved_by_user')
            ->add('user')
            ->add('quote_order')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quote::class,
        ]);
    }
}

src/Controller/QuoteController.php
<?php

namespace App\Controller;

use App\Entity\Quote;
use App\Entity\User;
use App\Form\QuoteType;
use App\Repository\QuoteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuoteController extends AbstractController
{
//    /**
//     * @Route("/quote", name="quote_index", methods={"GET"})
//     */
//    public function index(QuoteRepository $quoteRepository): Response
//    {
//        return $this->render('quote/index.html.twig', [
//            'quotes' => $quoteRepository->findAll(),
//        ]);
//    }

    /**
     * @Route("/new-quote", name="new_quote", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $quote      = new Quote();
        $formData   = $request->request->all();
        $errorMsg   = null;
        if ($request->isMethod('POST') && !($errorMsg   = $this->validateFormData($formData))) {
            $firstName      = $formData['firstName'] ?? null;
            $lastName       = $formData['lastName'] ?? null;
            $email          = $formData['emailAddress'] ?? null;

            $subject        = $formData['subject'] ?? null;
            $description    = $formData['description'] ?? null;

            $user   = (new User())->setEmail($email)->setFirstName($firstName)->setLastName($lastName);
            $quote  = (new Quote())->setTitle($subject)->setDescription($description)
                ->setCreatedAt(new \DateTime('now'))->setStatus('pending')->setUser($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quote);
            $entityManager->flush();

            return $this->redirectToRoute('quote_success', ['email' => $email]);
        }

        return $this->render('quote/new.html.twig', [
            'quote'     => $quote,
            'errorMsg'  => $errorMsg,
            'form'      => $formData,
        ]);
    }

    /**
     * @Route("/quote-success", name="quote_success", methods={"GET"})
     */
    public function quoteSuccess(Request $request)
    {
        $email = $request->query->get('email');
        return $this->render('quote/success.html.twig',[
            'email' => $email
        ]);
    }

    /**
     * @Route("/quote/{id}", name="quote_show", methods={"GET"})
     */
    public function show(Quote $quote): Response
    {
        return $this->render('quote/show.html.twig', [
            'quote' => $quote,
        ]);
    }

//    /**
//     * @Route("/quote/{id}/edit", name="quote_edit", methods={"GET","POST"})
//     */
//    public function edit(Request $request, Quote $quote): Response
//    {
//        $form = $this->createForm(QuoteType::class, $quote);
//        $form->handleRequest($request);
//
//        if ($form->isSubmitted() && $form->isValid()) {
//            $this->getDoctrine()->getManager()->flush();
//
//            return $this->redirectToRoute('quote_index');
//        }
//
//        return $this->render('quote/edit.html.twig', [
//            'quote' => $quote,
//            'form' => $form->createView(),
//        ]);
//    }
//
//    /**
//     * @Route("/quote/{id}", name="quote_delete", methods={"DELETE"})
//     */
//    public function delete(Request $request, Quote $quote): Response
//    {
//        if ($this->isCsrfTokenValid('delete'.$quote->getId(), $request->request->get('_token'))) {
//            $entityManager = $this->getDoctrine()->getManager();
//            $entityManager->remove($quote);
//            $entityManager->flush();
//        }
//
//        return $this->redirectToRoute('quote_index');
//    }

    /**
     * @param array $data
     *
     * @return null|string
     */
    private function validateFormData(array $data): ?string
    {
        $requiredFields = [
            'emailAddress',
            'firstName',
            'company',
            'subject',
            'description'
        ];
        foreach($requiredFields as $requiredField) {
            if (empty($data[$requiredField])) {
                return "This field {$requiredField} is required!";
            }
        }
        return null;
    }
}

templates/quote/_delete_form.html.twig
<form method="post" action="{{ path('quote_delete', {'id': quote.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quote.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quote/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quote/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quote{% endblock %}

{% block body %}
    <h1>Edit Quote</h1>

    {{ include('quote/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('quote_index') }}">back to list</a>

    {{ include('quote/_delete_form.html.twig') }}
{% endblock %}

templates/quote/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quote index{% endblock %}

{% block body %}
    <h1>Quote index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Created_at</th>
                <th>Status</th>
                <th>Price</th>
                <th>Send_to_user</th>
                <th>Approved_by_user</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quote in quotes %}
            <tr>
                <td>{{ quote.id }}</td>
                <td>{{ quote.title }}</td>
                <td>{{ quote.description }}</td>
                <td>{{ quote.createdAt ? quote.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ quote.status }}</td>
                <td>{{ quote.price }}</td>
                <td>{{ quote.sendToUser ? quote.sendToUser|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ quote.approvedByUser ? quote.approvedByUser|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('quote_show', {'id': quote.id}) }}">show</a>
                    <a href="{{ path('quote_edit', {'id': quote.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('quote_new') }}">Create new</a>
{% endblock %}

templates/quote/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quote{% endblock %}

{% block body %}
<main id="main">
<section id="contact" class="clearfix">
    <div class="container-fluid">
        <div class="section-header" style="margin-top:30px;padding-top:5px;">
            <h3>Request a Quote for your project</h3>
        </div>
        {% if errorMsg %}
            <div class="alert alert-danger" role="alert">
                {{ errorMsg }}
            </div>
        {%  endif %}
        <div class="col-lg-6" style="margin: auto; margin-bottom: 15px; padding-left: 0">
            <strong>Fields marked with * are required!</strong>
        </div>
        <div class="row wow fadeInUp">
            <div class="col-lg-6" style="margin: auto;">
                <form action="/new-quote" method="POST" role="form" data-toggle="validator">
                    <div class="form-group error">
                        <label for="emailAddress">Email address *</label>
                        <input type="email" class="form-control col-sm-8" id="emailAddress" name="emailAddress"
                               aria-describedby="emailHelp" placeholder="Enter email" required="true">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div>

                    <div class="form-group">
                        <label for="firstName">First Name *</label>
                        <input type="text" class="form-control col-sm-8" id="firstName" name="firstName" placeholder="First Name" required="true">
                    </div>

                    <div class="form-group">
                        <label for="lastName">Last Name</label>
                        <input type="text" class="form-control col-sm-8" id="lastName" name="lastName" placeholder="Last Name">
                    </div>

                    <div class="form-group">
                        <label for="company">Company Name (if you are a business)</label>
                        <input type="text" class="form-control col-sm-8" id="company" name="company" placeholder="Company Name">
                    </div>

                    <div class="form-group">
                        <label for="subject">Subject *</label>
                        <input type="text" class="form-control col-sm-8" id="subject" name="subject" placeholder="Subject" required="true">
                    </div>
                    <div class="form-group">
                        <label for="description">Project Description *</label>
                        <textarea class="form-control col-sm-8" id="description" name="description" rows="10" required="true"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
        {#<div class="form-group">#}
            {#{{ include('quote/_form.html.twig') }}#}
        {#</div>#}
    </div>
</section>
</main>
{% endblock %}

templates/quote/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quote{% endblock %}

{% block body %}
    <h1>Quote</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quote.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ quote.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ quote.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ quote.createdAt ? quote.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ quote.status }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ quote.price }}</td>
            </tr>
            <tr>
                <th>Send_to_user</th>
                <td>{{ quote.sendToUser ? quote.sendToUser|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Approved_by_user</th>
                <td>{{ quote.approvedByUser ? quote.approvedByUser|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('quote_index') }}">back to list</a>

    <a href="{{ path('quote_edit', {'id': quote.id}) }}">edit</a>

    {{ include('quote/_delete_form.html.twig') }}
{% endblock %}

templates/quote/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quote Success{% endblock %}

{% block body %}
<section id="about" style="margin-top:30px;">
    <div class="container">
        <header class="section-header">
            <h3>Thank you for sending a Quote!</h3>
            <div class="alert alert-success" role="alert">
                We have received your quote, and will contact you shortly at your email: {{ email }}
            </div>
        </header>
    </div>
</section>
{% endblock %}